core: adding status check workflow and refactor template workflow

diff --git a/.github/workflows/ci-template.yml b/.github/workflows/ci-template.yml
--- a/.github/workflows/ci-template.yml
+++ b/.github/workflows/ci-template.yml
@@ -2,6 +2,9 @@ name: (Template) Docker buld and push
 on:
     workflow_call:
         inputs:
+            push_to_registry:
+              default: true
+              type: boolean
             service_name:
                 required: true
                 type: string
@@ -13,16 +16,41 @@ on:
                 type: string
         secrets:
           ACR_LOGIN_SERVER:
-            required: true
+            required: false
           ACR_USERNAME:
-            required: true
+            required: false
           ACR_PASSWORD:
-            required: true
-
-
+            required: false
+            
 jobs:
+
+    InputValidation:
+      runs-on: ubuntu-latest
+
+      steps:
+        - name: Validating inputs
+          if: ${{ inputs.push_to_registry == true }}
+          run: |
+            #!/bin/bash
+              set -e  # stop on first failure
+
+              # List of secrets to check
+              secrets=("ACR_LOGIN_SERVER" "ACR_USERNAME" "ACR_PASSWORD")
+
+              # Loop and validate each secret
+              for secret_name in "${secrets[@]}"; do
+                value="${!secret_name}"
+                if [[ -z "$(echo "$value" | tr -d '[:space:]')" ]]; then
+                echo "Error: Secret '$secret_name' is empty or whitespace!"
+                exit 1
+                fi
+              done
+            done
+            echo "All required ACR secrets are set."
+      
     Versionning:
         runs-on: ubuntu-latest
+        needs: InputValidation
         outputs:
             version:  ${{ steps.gitversion.outputs.semVer }}
             sha: ${{ steps.sha.outputs.short }}
@@ -49,9 +77,8 @@ jobs:
              id: sha
              run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
 
-
     BuildAndPushImage:
-        needs: Versionning
+        needs: [Versionning, InputValidation]
         name: Build & Push service
         runs-on: ubuntu-latest
         
@@ -59,18 +86,30 @@ jobs:
             - name: Checkout
               uses: actions/checkout@v4
               with:
-                fetch-depth: 0   # REQUIRED for GitVersion
+                fetch-depth: 0   # REQUIRED for GitVersion. Disables shallow clone
             
+            - name: Set image name
+              run: |
+                VERSION_TAG="${{ needs.versionning.outputs.version }}-${{ needs.versionning.outputs.sha }}"
+                IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/${{ inputs.service_name }}:$VERSION_TAG"
+                echo "IMAGE=$IMAGE" >> $GITHUB_ENV
+
+            
+            - name: Build image
+              run: |
+                docker build -t $IMAGE ${{ inputs.service_path }}
+                docker push $IMAGE
+            
+            # Only push to registry when flag is true
             - name: Login to ACR
+              if: ${{ inputs.push_to_registry == true }}
               uses: docker/login-action@v3
               with:
                 registry: ${{ secrets.ACR_LOGIN_SERVER }}
                 username: ${{ secrets.ACR_USERNAME }}
                 password: ${{ secrets.ACR_PASSWORD }}
-            
-            - name: Build & Push image
-              run: |
-                VERSION_TAG="${{ needs.versionning.outputs.version }}-${{ needs.versionning.outputs.sha }}"
-                IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/${{ inputs.service_name }}:$VERSION_TAG"
-                docker build -t $IMAGE ${{ inputs.service_path }}
+
+            -  name: Push image
+               if: ${{ inputs.push_to_registry == true }}
+               run: |
                 docker push $IMAGE
